apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaniko
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../../base
namePrefix: flask-portfolio-
nameSuffix: "-001"
patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: buildx
    namespace: kaniko
  spec:
    template:
      spec:
        containers:
        - name: buildx
          image: gcr.io/kaniko-project/executor:latest
          command: ["docker"]
          args: 
            - "run --platform linux/amd64,linux/arm64"
            - "gcr.io/kaniko-project/executor:latest"
            - "--git=branch=build"
            - "--context=git://github.com/AbeYuki/flask-portfolio/"
            - "--destination=registry.gitlab.com/aimhighergg/docker-registry/flask-portfolio:1.0"
