apiVersion: batch/v1
kind: Job
metadata:
  name: buildx
  namespace: kaniko
spec:
  template:
    spec:
      containers:
      - name: buildx
        image: docker
        command: ["docker"]
        args: 
          - "run"
          - "-itd"
          - "--rm"
          - "--volume=/:/workspace"
          - "--workdir=/workspace"
          - "gcr.io/kaniko-project/executor:latest"
          - "--context=git://github.com/AbeYuki/flask-portfolio/"
          - "--destination=registry.gitlab.com/aimhighergg/docker-registry/flask-portfolio:1.0"
          - "--git=branch=build"
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
          - name: kaniko-secret
            mountPath: /root/.docker
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-credential
              key: git-username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-credential
              key: git-password
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
          secretName: docker-registry
          items:
            - key: .dockerconfigjson
              path: config.json
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
  backoffLimit: 1
